remove labels when checking libs

diff --git a/.github/workflows/charm-checks.yaml b/.github/workflows/charm-checks.yaml
--- a/.github/workflows/charm-checks.yaml
+++ b/.github/workflows/charm-checks.yaml
@@ -47,31 +47,33 @@ jobs:
           uvx tox -e lint
 
   lib-check:
-    name: Check libraries
-    runs-on: ubuntu-latest
-    needs: [codeql, static-analysis, linting]
-    if: ${{ github.event_name == 'pull_request' }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Install charmcraft
-        run: sudo snap install charmcraft --classic --channel="latest/stable"
-      - name: Check charm libraries
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          PR_NUMBER: ${{ github.event.number }}
-        run: |
-          cd "${{ inputs.charm-path }}"
-          fetch_lib="$(charmcraft fetch-lib)"
-          # If charm libraries are not up-to-date
-          if echo "$fetch_lib" | grep -qE "not found in Charmhub|updated to version|has local changes"; then
-            gh pr edit "$PR_NUMBER" --remove-label "Charm Libraries: OK" --add-label "Charm Libraries: Out of Sync"
-          else
-            gh pr edit "$PR_NUMBER" --remove-label "Charm Libraries: Out of Sync" --add-label "Charm Libraries: OK"
-          fi
+  name: Check libraries
+  runs-on: ubuntu-latest
+  needs: [codeql, static-analysis, linting]
+  if: ${{ github.event_name == 'pull_request' }}
+  steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
 
+    - name: Install charmcraft
+      run: sudo snap install charmcraft --classic --channel="latest/stable"
+
+    - name: Check charm libraries
+      env:
+        CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
+      run: |
+        cd "${{ inputs.charm-path }}"
+        fetch_lib="$(charmcraft fetch-lib)"
+
+        if echo "$fetch_lib" | grep -qE "not found in Charmhub|updated to version|has local changes"; then
+          echo "Charm libraries are out of sync: please sync them"
+          echo "$fetch_lib"
+          exit 1
+        else
+          echo "Charm libraries are in sync."
+        fi
   integration-tests:
     name: Integration Tests
     runs-on: ubuntu-latest
